version: "3.7" 
services:
  nginx-elofy:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./backend:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-elofy
      -  mysql-elofy
  php-elofy:
    build:
      context: .
    image: phpdocker
    container_name: php-elofy
    ports:
      - "9000:9000"
    volumes:
      - "./backend:/var/www/html/"
    # command: php -S 0.0.0.0:9000 -t public/
    # links:
      # - mysql
  mysql-elofy:
    image: mysql:5.7
    container_name: mysql-elofy
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345'

  client-elofy:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
volumes:
    mysql: